title: Minimal theme
title_image: [https://www.bcm.edu/sites/default/files/profile_photos/nbarshes.jpeg]
logo: [https://www.bcm.edu/sites/default/files/profile_photos/nbarshes.jpeg]
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
