title: Neal R Barshes, MD, MPH
title_image: /assets/GuardYourFeetImage01.jpg
logo: /assets/profile3.jpg
description: Resources for amputation prevention.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
