title: Neal R Barshes, MD, MPH
title_image: Guard Your Feet
logo: /assets/GuardYourFeetImage01.jpg
description: Resources for amputation prevention.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
