title: Neal R. Barshes, M.D., M.P.H.
title_image: /assets/profile1.jpg
logo: /assets/profile1.jpg
description: Resources for amputation prevention.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
