theme: jekyll-theme-minimal
title_image: [https://www.bcm.edu/sites/default/files/profile_photos/nbarshes.jpeg]
logo: [https://www.bcm.edu/sites/default/files/profile_photos/nbarshes.jpeg]
description: Resources for preventing amputations.
show_downloads: true
google_analytics:
