title: Foot Infection Management
title_image: Foot Infections
logo: /assets/GuardYourFeetColor03.jpg
description: Information and resources directly relevant to the clinical management of foot infections associated with peripheral artery disease or diabetes. These are intended as adjuncts and do NOT replace clinical experience and clinical judgement. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
